/*
User Model:
_id (Object ID): A distinctive identifier generated by MongoDB.
username (string): The username of the user. This field holds a unique identifier for the user.
email (string): The email address of the user. This field stores the user's email, ensuring it is unique.
password (string): The password linked to the user's account, securely hashed. Strong password validation is encouraged, with specified format requirements. If implementing password strength validation, please provide the password format and appropriate error message for user guidance.
role ('user' | 'admin'): The role of the user, which can be either 'user' or 'admin'. This field determines the user's level of access or permissions. The default role is set to 'user'.
*/

// 1. Create an interface representing a document in MongoDB.

export type TRegisterUser = {
  username: string
  email: string
  password: string
  passwordHistory: string[]
  role: 'user' | 'admin'
  createdAt?: Date
  updatedAt?: Date
}
