// 3. Review Model:
// Fields:
// _id (Object ID): A distinctive identifier generated by MongoDB.
// courseId (Object ID): A reference to the course collection.
// rating (Number): Rating, which falls within the range of 1 to 5.
// review (String): The comment or review text provided by the user.

import { ObjectId } from "mongodb";

export type TReview = {
  courseId: ObjectId;
  rating: number;
  review: string;
};
