// 2. Category Model:
// Fields:
// _id (Object ID): A distinctive identifier generated by MongoDB.
// name (String): A unique name of the category.

// Create Interface for Category

export type TCategory = {
  name: string;
};
